// scripts/demo-data/emit-sql.ts
//
// Serialise GeneratedSeed → a single .sql file suitable for
// `wrangler d1 execute --remote --file=...`. Args are inlined because
// `wrangler d1 execute` does not support `--bind` for file mode.
//
// NO BEGIN/COMMIT: D1 rejects raw `BEGIN TRANSACTION`/`COMMIT` because
// the underlying Durable Object requires `state.storage.transaction()`
// at the JS level. wrangler's `d1 execute --file` already rolls the
// whole file back on failure ("if the execution fails to complete,
// your DB will return to its original state and you can safely retry"),
// so the explicit transaction wrapper was redundant and broke staging.
//
// SECURITY NOTE: every arg comes from our own deterministic generator —
// there is no untrusted input here. Even so, we use a strict allowlist
// (string|number|null) and a single-quote-doubling escape so the file
// can never inadvertently introduce a malformed statement.

import type { GeneratedSeed, SqlArg } from "./generate";

function quote(arg: SqlArg): string {
  if (arg === null) return "NULL";
  if (typeof arg === "number") {
    if (!Number.isFinite(arg)) {
      throw new Error(`emit-sql: non-finite numeric arg ${arg}`);
    }
    return arg.toString();
  }
  if (typeof arg === "string") {
    return `'${arg.replace(/'/g, "''")}'`;
  }
  // The SqlArg type forbids everything else; this throw is belt-and-
  // suspenders so a future widening of SqlArg surfaces here loudly.
  throw new Error(`emit-sql: unsupported arg type ${typeof arg}`);
}

function inline(sql: string, args: SqlArg[]): string {
  let i = 0;
  return sql.replace(/\?/g, () => {
    if (i >= args.length) {
      throw new Error(`emit-sql: not enough args for sql: ${sql}`);
    }
    return quote(args[i++]!);
  });
}

export function emitSql(seed: GeneratedSeed): string {
  const lines: string[] = [];
  lines.push("-- Auto-generated by scripts/demo-data/emit-sql.ts");
  lines.push("-- Do not edit by hand. Re-run: npm run demo:seed:<env>.");
  lines.push("-- WIPE");
  for (const s of seed.wipeStatements) {
    lines.push(inline(s.sql, s.args) + ";");
  }
  lines.push("-- SEED");
  for (const s of seed.seedStatements) {
    lines.push(inline(s.sql, s.args) + ";");
  }
  return lines.join("\n") + "\n";
}
